(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(c-offsets-alist
   (quote
    ((inexpr-class . +)
     (inexpr-statement . +)
     (lambda-intro-cont . +)
     (inlambda . c-lineup-inexpr-block)
     (template-args-cont c-lineup-template-args +)
     (incomposition . +)
     (inmodule . +)
     (innamespace . c-lineup-dont-change)
     (inextern-lang . +)
     (composition-close . 0)
     (module-close . 0)
     (namespace-close . c-lineup-dont-change)
     (extern-lang-close . 0)
     (composition-open . 0)
     (module-open . 0)
     (namespace-open . c-lineup-dont-change)
     (extern-lang-open . 0)
     (objc-method-call-cont c-lineup-ObjC-method-call-colons c-lineup-ObjC-method-call +)
     (objc-method-args-cont . c-lineup-ObjC-method-args)
     (objc-method-intro .
                        [0])
     (friend . 0)
     (cpp-define-intro c-lineup-cpp-define +)
     (cpp-macro-cont . +)
     (cpp-macro .
                [0])
     (inclass . +)
     (stream-op . c-lineup-streamop)
     (arglist-cont-nonempty c-lineup-gcc-asm-reg c-lineup-arglist)
     (arglist-cont c-lineup-gcc-asm-reg 0)
     (comment-intro c-lineup-knr-region-comment c-lineup-comment)
     (catch-clause . 0)
     (else-clause . 0)
     (do-while-closure . 0)
     (access-label . -)
     (case-label . 0)
     (substatement . +)
     (statement-case-intro . +)
     (statement . 0)
     (brace-entry-open . 0)
     (brace-list-entry . c-lineup-under-anchor)
     (brace-list-close . 0)
     (block-close . 0)
     (block-open . 0)
     (inher-cont . c-lineup-multi-inher)
     (inher-intro . +)
     (member-init-cont . c-lineup-multi-inher)
     (member-init-intro . +)
     (annotation-var-cont . +)
     (annotation-top-cont . 0)
     (topmost-intro . 0)
     (knr-argdecl . 0)
     (func-decl-cont . +)
     (inline-close . 0)
     (class-close . 0)
     (class-open . 0)
     (defun-block-intro . +)
     (defun-close . 0)
     (defun-open . 0)
     (c . c-lineup-C-comments)
     (string . c-lineup-dont-change)
     (topmost-intro-cont . c-lineup-topmost-intro-cont)
     (brace-list-intro . +)
     (brace-list-open . 0)
     (inline-open . +)
     (arglist-close . +)
     (arglist-intro . +)
     (statement-cont . +)
     (statement-case-open . 0)
     (label . 0)
     (substatement-label . 0)
     (substatement-open . 0)
     (knr-argdecl-intro . +)
     (statement-block-intro . +))))
 '(helm-gtags-auto-update t)
 '(helm-gtagssuggested-keymapping t)
 '(package-selected-packages
   (quote
    (php-mode cmake-mode buffer-move company-irony irony glsl-mode zenburn-theme web-mode undo-tree quickrun py-autopep8 multi-term moccur-edit markdown-preview-mode magit kotlin-mode helm-gtags helm-descbinds helm-c-moccur gtags flycheck-pos-tip elscreen dockerfile-mode docker-compose-mode company auto-complete))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(term-color-black ((t (:foreground "#3F3F3F" :background "#2B2B2B"))))
 '(term-color-blue ((t (:foreground "#7CB8BB" :background "#4C7073"))))
 '(term-color-cyan ((t (:foreground "#93E0E3" :background "#8CD0D3"))))
 '(term-color-green ((t (:foreground "#7F9F7F" :background "#9FC59F"))))
 '(term-color-magenta ((t (:foreground "#DC8CC3" :background "#CC9393"))))
 '(term-color-red ((t (:foreground "#AC7373" :background "#8C5353"))))
 '(term-color-white ((t (:foreground "#DCDCCC" :background "#656555"))))
 '(term-color-yellow ((t (:foreground "#DFAF8F" :background "#9FC59F"))))
 '(term-default-bg-color ((t (:inherit term-color-magenta))))
 '(term-default-fg-color ((t (:inherit term-color-yellow)))))
