# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  emacs-smoke-test:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        emacs-version:
          - 27.1
          - 28.0
          - snapshot
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2    
      - name: Set up Emacs
        # You may pin to the exact commit or the version.
        # uses: 
        uses: purcell/setup-emacs@bea3d9e95785b8412caf802b320cd6de386be7a3
        with:
          # The version of Emacs to install, e.g. "24.3", or "snapshot" for a recent development version.
          version: ${{ matrix.emacs_version }}
      - name: Run smoke test
        run: make emacs-test
